eureka:
  instance:
    hostname: ${EUREKA_PORT_8761_TCP_ADDR:eureka}:${EUREKA_PORT_8761_TCP_PORT:8761}
  client:
    registerWithEureka: true
    fetchRegistry: true

moji:
  trackerAddresses: ${MOGILEFSD_PORT_7001_TCP_ADDR:mogilefsd}:${MOGILEFSD_PORT_7001_TCP_PORT:7001}
  domain: sr-dev

google:
  gcmApiKey: AIzaSyDjzP-6Vz6Mvq-q2R7fgRgxXub9u49fLEg
  geocodeEndpoint: https://maps.googleapis.com/maps/api/geocode/json
  geocodeApiKey: AIzaSyCthS9QAsYMFQKZ0wR4s0HVbw44OeTa_ZM

aws:
  accessKey: AKIAIBWV65P3H73SXSUA
  secretKey: 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
  imageBucket: subrosa-games-images

facebook:
  appId: foo
  appSecret: bar

spring:
  datasource:
    url: jdbc:postgresql://${DB_PORT_5432_TCP_ADDR:db}:${DB_PORT_5432_TCP_PORT:5432}/engine
    username: engine
    password: engine
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    show-sql: true
    properties:
      javax.persistence.validation.group.pre-persist: com.subrosagames.subrosa.domain.game.validation.Always
      javax.persistence.validation.group.pre-update: com.subrosagames.subrosa.domain.game.validation.Always
    hibernate:
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
      ddl-auto: validate

  rabbitmq:
    host: ${RABBITMQ_PORT_5672_TCP_ADDR:rabbitmq}
    username: engine
    password: engine

